version: '3'

services:
  batch_metadata_db:
    container_name: mysql_batch_metadata_db
    image: mysql
    environment:
      - MYSQL_DATABASE=batch_db
      - MYSQL_USER=batch_user
      - MYSQL_PASSWORD=batch_user_pass
      - MYSQL_ROOT_PASSWORD=batch_user_pass
    ports:
      - 3306:3306
    healthcheck:
      test: mysql batch_db --user=batch_user --password=batch_user_pass --silent --execute "SELECT VERSION();"
      interval: 5s
      retries: 15
      start_period: 5s
      timeout: 10s