version: '3'

services:
  batch_app:
    container_name: database_batch_app
    image: batch/database
    depends_on:
      batch_metadata_db:
          condition: service_healthy
    environment:
      - "PROFILE=${CURRENT_PROFILE}"
      - "JOB_PARAMETER_NAME=${JOB_PARAMETER_NAME}"
      - "BATCH_DB_HOST=${DB_METADATA_HOST}"
      - "BATCH_DB_PORT=${DB_METADATA_PORT}"
      - "BATCH_DB_NAME=${DB_METADATA_DATABASE}"
      - "BATCH_DB_USER=${DB_METADATA_USERNAME}"
      - "BATCH_DB_PASS=${DB_METADATA_PASSWORD}"
      
  batch_metadata_db:
    container_name: mysql_batch_metadata_db
    image: mysql
    environment:
      - "MYSQL_DATABASE=${DB_METADATA_DATABASE}"
      - "MYSQL_USER=${DB_METADATA_USERNAME}"
      - "MYSQL_PASSWORD=${DB_METADATA_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_METADATA_PASSWORD}"
    healthcheck:
      test: mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD ping -h localhost
      interval: 10s
      retries: 15
      start_period: 5s
      timeout: 20s
      
  
